version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - postgres-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "1112@ada.br"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "2345:80"
    depends_on:
      - postgres
    networks:
      - postgres-network
  wiremock:
    image: "wiremock/wiremock:latest"
    ports:
      - '8082:8080'
    volumes:
      - ./src/test/resources/wiremock/stubs/mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--verbose" ]

networks:
  postgres-network:
    driver: bridge